# be mindful of "quotes"

# link: https://developers.google.com/tenor/guides/quickstart#setup
google_api_key = "AIzaSyC0p1_3ke04716t4TScHL1wt0a1KBFCDJI"
tenor_api_key = "AIzaSyC0p1_3ke04716t4TScHL1wt0a1KBFCDJI"

# link: https://developers.google.com/custom-search/v1/overview
google_cx = "43b48bb8b882e4be7"

# match in ibuprofen-listener
resolve_host = "127.0.0.1"
resolve_port = 13182

# use \\ on Windows
download_dir = "C:\\Users\\helo\\Downloads\\"
